title: All Mixed Up California
description: > # this means to ignore newlines until "baseurl:"
    Community of multiracial and multicultural students.
permalink: ':title/'
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://allmixedupca.byethost18.com" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: main-logo-original.png # your photo
author-name: All Mixed Up CA
about-author: Community and organanization of multiracial and multicultural students. Founded by Sybelle Nestlehut, Nikki Trueblood, Kina Atkin-Yamaguchi, and Oliver Trevor. We are a supportive and inclusive environment and social group for people who see culture and race as being more than just one thing or another. # about author
email: allmixedupca@gmail.com # your email
# phone: (496)-169-6557 # your pnone number
# website: https://dwayne.example.com # you website

# Social link
instagram_handle: "@allmixedupca"
instagram_url: https://www.instagram.com/allmixedupca
facebook_username: AllMixedUpCA
facebook_url:  https://www.facebook.com/AllMixedUpCA

# Disqus
# discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
# mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
plugins: [jekyll-paginate]
